apiVersion: v1
data:
  CLAIR_DB_PASSWORD: bm90LWEtc2VjdXJlLXBhc3N3b3Jk
  EMAIL_PWD: bm90LWEtc2VjdXJlLXBhc3N3b3Jk
  HARBOR_ADMIN_PASSWORD: bm9wYXNzd29yZAo=
  JOBSERVICE_SECRET: bm90LWEtc2VjdXJlLXNlY3JldA==
  MYSQL_PWD: cmVnaXN0cnk=
  UI_SECRET: bm90LWEtc2VjdXJlLXNlY3JldA==
  secretKey: bm90LWEtc2VjdXJlLWtleQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: harbor
    chart: harbor-0.1.1
    component: adminserver
    heritage: Tiller
    release: harbor
  name: harbor-harbor-adminserver
type: Opaque
