apiVersion: v1
data:
  JOBSERVICE_SECRET: bm90LWEtc2VjdXJlLXNlY3JldA==
  UI_SECRET: bm90LWEtc2VjdXJlLXNlY3JldA==
  secretKey: bm90LWEtc2VjdXJlLWtleQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: harbor
    chart: harbor-0.1.1
    heritage: Tiller
    release: harbor
  name: harbor-harbor-jobservice
type: Opaque
