apiVersion: v1
data:
  mysqlRootPassword: cmVnaXN0cnk=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: harbor
    chart: harbor-0.1.1
    heritage: Tiller
    release: harbor
  name: harbor-harbor-mysql
type: Opaque
