apiVersion: v1
data:
  postgres-password: bm90LWEtc2VjdXJlLXBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: harbor-postgresql
    chart: postgresql-0.9.1
    heritage: Tiller
    release: harbor
  name: harbor-postgresql
type: Opaque
